name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - $default-branch
  release:
    types:
      - created

jobs:
  test:
    uses: CodrJS/cicd/.github/workflows/node-test.yml@main
    secrets: inherit
    with:
      JWT_ALGORITHM: ${{ vars.JWT_ALGORITHM }}
      JWT_ISSUER: ${{ vars.JWT_ISSUER }}
  build-and-publish:
    uses: CodrJS/cicd/.github/workflows/docker-build-and-publish.yml@main
    needs: test
    secrets: inherit
